#!/bin/bash
#
# post-checkout-excel: have git handle xlsx files by deflating them and storing
#                      the XML in the repository, not the zip file. 
#
#                      companion to pre-commit-excel
#                      currently identical to post-commit

# -- config -- #
TMP_PREFIX='.~' # prefix XML directory--should NOT conflict with 
                   # anything in your repo
export TMP_PREFIX

# -- end config -- #

echo
echo "=== Post-checkout XLSX processing ===="

repack_xlsx () {
    # re-zip the XML directory 
    rm "$1"
    cd "${TMP_PREFIX}$1"
    zip "../$1" -r *
    cd ..
}
export -f repack_xlsx

# make it easy to iterate over subdirectories
shopt -s globstar

# repack all the zipfiles
start_dir="$(pwd)"
for i in **/${TMP_PREFIX}*.docx; do 
    dir=$(dirname "$i")
    base=$(basename "$i")
    file=${base:${#TMP_PREFIX}}
    cd "$dir"
    repack_xlsx "$file"
    cd "$start_dir"
done

echo "=== End of post-checkout processing ==="
echo
